name: Build on Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # LATEST

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm prepare

      - name: Build
        run: pnpm build
